
name: test #531

on:
  workflow_dispatch:
  

jobs:
 
 test:
    runs-on: [ubuntu-24.04]
    env:
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Specify the .NET 8.0 SDK version

    - name: Set Environment Variables
      run: |
           echo "DOTNET_CLI_HOME=$HOME" >> $GITHUB_ENV
           echo "HOME=$HOME" >> $GITHUB_ENV

    - run: dotnet restore test-proj.csproj
    - run: dotnet build --no-restore test-proj.csproj
