name: 'demo-test'

on:
  workflow_dispatch:
jobs:
  demonstrate:
    runs-on: Ubuntu-latest
    steps:
      - name: 'setup-dotnet'
        uses: 'actions/setup-dotnet@v4' # ratchet:actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: 'verify-dotnet'
        run: |
          dotnet tool install --global dotnet-script --version 1.6.0
          cat <<'EOF' > test.csx
          var version = Environment.Version;
          if (version.Major != 8 || version.Minor != 0)
          {
            throw new Exception($"Want .NET 8.0.x, got {version}");
          }
          EOF
          dotnet-script test.csx
